let cars=[],lang="EN";const $=x=>document.getElementById(x),portal="https://portal.habibi-performance.com/login";
const T={DE:{navHome:"HOME",navDatabase:"ECU DATENBANK",navDyno:"DYNO ERGEBNISSE",navServices:"SERVICES",filePortal:"FILE PORTAL",officialPartner:"OFFIZIELLER PARTNER",clickScan:"Klicken oder scannen",verifiedCustomer:"VERIFIZIERTER KUNDE",stockLabel:"SERIE",powerLabel:"LEISTUNG",torqueLabel:"DREHMOMENT",gainLabel:"ZUWACHS",review:"„Top Service und mega Ergebnis! Mein Auto fühlt sich wie neu an. Mehr Leistung, schnelleres Ansprechverhalten. Klare Empfehlung!“",scan:"SCANNEN & FOLGEN",partners:"PARTNER",partners_sub:"Partner-Logos später hier einfügen",headline:'WIE VIEL <span>LEISTUNG</span> STECKT IN DEINEM AUTO?',sub:"Wähle dein Fahrzeug und sieh Serienleistung und verfügbares Tuning-Potenzial.",make:"HERSTELLER",model:"MODELL",gen:"GENERATION",engine:"MOTOR / LEISTUNG",search:"FAHRZEUG FINDEN",quick:"Fahrzeug über Hersteller, Modell und Generation wählen",safe:"100% SICHER & ZUVERLÄSSIG",safeSub:"Deine Daten sind bei uns sicher.",fast:"SCHNELLE LIEFERUNG",fastSub:"Schnelle Bearbeitung & Lieferung.",quality:"PROFESSIONELLE QUALITÄT",qualitySub:"Geprüfte Tuning-Files.",world:"Kunden weltweit.",brands:"MARKEN",cars:"FAHRZEUGE",dynoTitle:'ECHTE PARAMETER. <span>KLARE LEISTUNG.</span>',dynoSub:"Professionelle Darstellung – nur die Werte, die zählen.",servicesTitle:'UNSERE <span>LEISTUNGEN</span>',s1:"Performance-Kalibrierungen für unterstützte Fahrzeuge.",s2:"Professionelle Motor- und Getriebe-Dateilösungen.",s3:"Individuelle Lösungen passend zum Fahrzeug.",s4:"Upload und Download über das File Portal.",popular:'BELIEBTE <span>FAHRZEUGE</span>',faqTitle:'HÄUFIGE <span>FRAGEN</span>',q1:"Ist die angezeigte Leistung garantiert?",a1:"Nein. Das tatsächliche Ergebnis hängt von ECU, Kraftstoff, Hardware und Fahrzeugzustand ab.",q2:"Muss ich zu euch kommen?",a2:"Nein. Der File Service ist weltweit über das Portal verfügbar.",q3:"Wie bestelle ich eine Datei?",a3:"Fahrzeug auswählen und im File Portal fortfahren.",ready:"BEREIT FÜR MEHR LEISTUNG?",readySub:"Datei hochladen, Credits kaufen und fertige Datei über das Portal herunterladen.",selMake:"Hersteller wählen",selModel:"Modell wählen",selGen:"Generation wählen",selEngine:"Motor wählen",original:"SERIE",tuned:"TUNING",order:"DATEI BESTELLEN →",estimate:"Leistungsangaben aus dem Fahrzeugkatalog. Das reale Ergebnis kann je nach Fahrzeugzustand und Hardware abweichen.",loading:"WIRD GELADEN…",unavailable:"Daten momentan nicht verfügbar.",ecuUnit:"ECU / MOTORSTEUERGERÄT",ecuUnknown:"ECU nicht im Katalog angegeben",ecuHint:"Das ECU kann je nach Motorkennbuchstabe, Baujahr und Softwarestand variieren. Vor dem Tuning mit der Originaldatei bestätigen."},
BS:{navHome:"POČETNA",navDatabase:"ECU BAZA",navDyno:"DYNO REZULTATI",navServices:"USLUGE",filePortal:"FILE PORTAL",officialPartner:"SLUŽBENI PARTNER",clickScan:"Klikni ili skeniraj",verifiedCustomer:"POTVRĐENA MUŠTERIJA",stockLabel:"FABRIČKI",powerLabel:"SNAGA",torqueLabel:"OBRTNI MOMENT",gainLabel:"DOBITAK",review:"„Top usluga i odličan rezultat! Auto se ponaša kao novo. Više snage i bolji odziv. Svaka preporuka!“",scan:"SKENIRAJ & ZAPRATI",partners:"PARTNERI",partners_sub:"Logoe partnera možeš dodati kasnije",headline:'KOLIKO <span>SNAGE</span> SE KRIJE U TVOM AUTU?',sub:"Izaberi vozilo i pogledaj fabričku snagu i dostupni tuning potencijal.",make:"MARKA",model:"MODEL",gen:"GENERACIJA",engine:"MOTOR / SNAGA",search:"PRONAĐI VOZILO",quick:"Izaberi marku, model i generaciju",safe:"100% SIGURNO & POUZDANO",safeSub:"Tvoji podaci su sigurni.",fast:"BRZA ISPORUKA",fastSub:"Brza obrada i isporuka.",quality:"PROFESIONALNI KVALITET",qualitySub:"Provjereni tuning fajlovi.",world:"Mušterije širom svijeta.",brands:"BRENDOVA",cars:"VOZILA",dynoTitle:'PRAVI PARAMETRI. <span>JASNA SNAGA.</span>',dynoSub:"Profesionalan prikaz – samo parametri koji su bitni.",servicesTitle:'NAŠE <span>USLUGE</span>',s1:"Performance kalibracije za podržana vozila.",s2:"Profesionalna ECU i TCU rješenja.",s3:"Individualna rješenja za konkretno vozilo.",s4:"Upload i download preko File Portala.",popular:'POPULARNA <span>VOZILA</span>',faqTitle:'ČESTA <span>PITANJA</span>',q1:"Da li je prikazana snaga garantovana?",a1:"Ne. Stvarni rezultat zavisi od ECU-a, goriva, hardvera i stanja vozila.",q2:"Moram li doći kod vas?",a2:"Ne. File servis je dostupan worldwide preko portala.",q3:"Kako naručujem file?",a3:"Izaberi vozilo i nastavi preko File Portala.",ready:"SPREMAN ZA VIŠE SNAGE?",readySub:"Uploaduj file, kupi kredite i preuzmi gotov file preko portala.",selMake:"Izaberi marku",selModel:"Izaberi model",selGen:"Izaberi generaciju",selEngine:"Izaberi motor",original:"FABRIČKI",tuned:"TUNING",order:"NARUČI FILE →",estimate:"Podaci o snazi dolaze iz kataloga vozila. Stvarni rezultat može odstupati zavisno od stanja vozila i hardvera.",loading:"UČITAVANJE…",unavailable:"Podaci trenutno nisu dostupni.",ecuUnit:"ECU / UPRAVLJAČKA JEDINICA",ecuUnknown:"ECU nije naveden u katalogu",ecuHint:"ECU može varirati po kodu motora, godištu i verziji softvera. Potvrditi iz originalnog ECU fajla prije tuninga."},
EN:{navHome:"HOME",navDatabase:"ECU DATABASE",navDyno:"DYNO RESULTS",navServices:"SERVICES",filePortal:"FILE PORTAL",officialPartner:"OFFICIAL PARTNER",clickScan:"Click or scan",verifiedCustomer:"VERIFIED CUSTOMER",stockLabel:"STOCK",powerLabel:"POWER",torqueLabel:"TORQUE",gainLabel:"GAIN",review:"“Top service and an amazing result! My car feels new again. More power and faster response. Highly recommended!”",scan:"SCAN & FOLLOW",partners:"PARTNERS",partners_sub:"Partner logos can be added later",headline:'HOW MUCH <span>POWER</span> IS HIDING IN YOUR CAR?',sub:"Select your vehicle and see stock power and available tuning potential.",make:"MAKE",model:"MODEL",gen:"GENERATION",engine:"ENGINE / POWER",search:"FIND VEHICLE",quick:"Select make, model and generation",safe:"100% SAFE & RELIABLE",safeSub:"Your data is safe with us.",fast:"FAST DELIVERY",fastSub:"Fast processing & delivery.",quality:"PROFESSIONAL QUALITY",qualitySub:"Verified tuning files.",world:"Customers worldwide.",brands:"BRANDS",cars:"VEHICLES",dynoTitle:'REAL PARAMETERS. <span>CLEAR PERFORMANCE.</span>',dynoSub:"Professional display – only the values that matter.",servicesTitle:'OUR <span>SERVICES</span>',s1:"Performance calibrations for supported vehicles.",s2:"Professional ECU and TCU file solutions.",s3:"Individual vehicle-specific solutions.",s4:"Upload and download through the File Portal.",popular:'POPULAR <span>VEHICLES</span>',faqTitle:'FREQUENT <span>QUESTIONS</span>',q1:"Is the displayed power guaranteed?",a1:"No. Actual output depends on ECU, fuel, hardware and vehicle condition.",q2:"Do I need to visit you?",a2:"No. File service is available worldwide through the portal.",q3:"How do I order a file?",a3:"Select your vehicle and continue through the File Portal.",ready:"READY FOR MORE POWER?",readySub:"Upload a file, buy credits and download the finished file through the portal.",selMake:"Select manufacturer",selModel:"Select model",selGen:"Select generation",selEngine:"Select engine",original:"STOCK",tuned:"TUNING",order:"ORDER FILE →",estimate:"Power data comes from the vehicle catalogue. Real-world results may vary with vehicle condition and hardware.",loading:"LOADING…",unavailable:"Data currently unavailable.",ecuUnit:"ECU / ENGINE CONTROL UNIT",ecuUnknown:"ECU not listed in catalogue",ecuHint:"ECU can vary by engine code, year and software version. Confirm from the original ECU file before tuning."}};
Object.assign(T.EN,{navHow:"HOW IT WORKS",navPartners:"PARTNERS",howTitle:'HOW IT <span>WORKS</span>',howSub:"From original file to tuned file in four simple steps.",how1:"UPLOAD ORIGINAL FILE",how1p:"Upload your original ECU or TCU file through the portal.",how2:"SELECT SERVICE",how2p:"Choose the tuning or file solution required for the vehicle.",how3:"WE PROCESS",how3p:"Your file is prepared for the selected vehicle and service.",how4:"DOWNLOAD FILE",how4p:"Download the completed file directly from the File Portal.",supportTitle:'SUPPORTED <span>PLATFORMS</span>',supportSub:"Professional file solutions for widely used engine and transmission control units.",browseVehicles:"BROWSE VEHICLES →",partnerTitle:'BECOME A <span>PARTNER</span>',partnerSub:"Are you a workshop or tuner? Join our network and use our worldwide file service for your customers.",partnerCta:"OPEN FILE PORTAL →"});
Object.assign(T.DE,{navHow:"SO FUNKTIONIERT ES",navPartners:"PARTNER",howTitle:'SO <span>FUNKTIONIERT ES</span>',howSub:"Von der Originaldatei zur optimierten Datei in vier einfachen Schritten.",how1:"ORIGINALDATEI HOCHLADEN",how1p:"Lade deine originale ECU- oder TCU-Datei über das Portal hoch.",how2:"SERVICE AUSWÄHLEN",how2p:"Wähle die gewünschte Tuning- oder Dateilösung für das Fahrzeug.",how3:"WIR BEARBEITEN",how3p:"Die Datei wird passend zum ausgewählten Fahrzeug und Service vorbereitet.",how4:"DATEI HERUNTERLADEN",how4p:"Lade die fertige Datei direkt über das File Portal herunter.",supportTitle:'UNTERSTÜTZTE <span>PLATTFORMEN</span>',supportSub:"Professionelle Dateilösungen für weit verbreitete Motor- und Getriebesteuergeräte.",browseVehicles:"FAHRZEUGE ANZEIGEN →",partnerTitle:'WERDE <span>PARTNER</span>',partnerSub:"Du bist Werkstatt oder Tuner? Werde Teil unseres Netzwerks und nutze unseren weltweiten File Service für deine Kunden.",partnerCta:"FILE PORTAL ÖFFNEN →"});
Object.assign(T.BS,{navHow:"KAKO RADI",navPartners:"PARTNERI",howTitle:'KAKO <span>RADI</span>',howSub:"Od originalnog fajla do tuniranog fajla u četiri jednostavna koraka.",how1:"UPLOAD ORIGINALNOG FAJLA",how1p:"Uploaduj originalni ECU ili TCU fajl preko portala.",how2:"IZABERI USLUGU",how2p:"Izaberi tuning ili file uslugu koja je potrebna za vozilo.",how3:"MI OBRAĐUJEMO",how3p:"Fajl se priprema prema izabranom vozilu i usluzi.",how4:"PREUZMI FAJL",how4p:"Preuzmi gotov fajl direktno preko File Portala.",supportTitle:'PODRŽANE <span>PLATFORME</span>',supportSub:"Profesionalna file rješenja za najčešće ECU i TCU upravljačke jedinice.",browseVehicles:"POGLEDAJ VOZILA →",partnerTitle:'POSTANI <span>PARTNER</span>',partnerSub:"Imaš servis ili se baviš tuningom? Pridruži se našoj mreži i koristi worldwide file servis za svoje mušterije.",partnerCta:"OTVORI FILE PORTAL →"});
Object.assign(T.EN,{navPricing:"PRICING",pricingEyebrow:"CREDIT PRICING",pricingTitle:'FILE SERVICE <span>PRICING</span>',pricingSub:"Transparent credit-based pricing for ECU and TCU file services.",creditRateLabel:"STANDARD CREDIT RATE",creditRateSub:"Larger credit packages and promotions can reduce the effective price per credit.",buyCredits:"BUY CREDITS →",tuningGroup:"ECU / TCU TUNING",deleteGroup:"SYSTEM SOLUTIONS",specialGroup:"SPECIAL FUNCTIONS",performanceGroup:"PERFORMANCE EXTRAS",pricingNote:"Credit values are fixed; euro ranges reflect an effective credit cost of €4–€6 depending on package or promotion. Some services are vehicle-dependent. Emissions-related solutions are intended only where legally permitted, including motorsport/off-road use where applicable."});
Object.assign(T.DE,{navPricing:"PREISE",pricingEyebrow:"CREDIT-PREISE",pricingTitle:'FILE SERVICE <span>PREISE</span>',pricingSub:"Transparente Credit-Preise für ECU- und TCU-File-Services.",creditRateLabel:"STANDARD CREDIT-PREIS",creditRateSub:"Größere Credit-Pakete und Aktionen können den effektiven Preis pro Credit reduzieren.",buyCredits:"CREDITS KAUFEN →",tuningGroup:"ECU / TCU TUNING",deleteGroup:"SYSTEMLÖSUNGEN",specialGroup:"SONDERFUNKTIONEN",performanceGroup:"PERFORMANCE EXTRAS",pricingNote:"Die Credit-Werte sind fest; die Euro-Spannen basieren auf einem effektiven Credit-Preis von €4–€6 je nach Paket oder Aktion. Einige Services sind fahrzeugabhängig. Emissionsbezogene Lösungen sind nur dort vorgesehen, wo sie gesetzlich zulässig sind, gegebenenfalls für Motorsport/Offroad."});
Object.assign(T.BS,{navPricing:"CIJENE",pricingEyebrow:"CIJENE KREDITA",pricingTitle:'FILE SERVICE <span>CIJENE</span>',pricingSub:"Jasne cijene u kreditima za ECU i TCU file servis.",creditRateLabel:"STANDARDNA CIJENA KREDITA",creditRateSub:"Veći paketi kredita i akcije mogu smanjiti stvarnu cijenu jednog kredita.",buyCredits:"KUPI KREDITE →",tuningGroup:"ECU / TCU TUNING",deleteGroup:"SISTEMSKA RJEŠENJA",specialGroup:"POSEBNE FUNKCIJE",performanceGroup:"PERFORMANCE DODACI",pricingNote:"Broj kredita po usluzi je fiksan; raspon u eurima računa efektivnu cijenu kredita od €4–€6, zavisno od paketa ili akcije. Neke usluge zavise od vozila. Rješenja vezana za emisijske sisteme namijenjena su samo tamo gdje su zakonski dozvoljena, uključujući motorsport/off-road gdje je primjenjivo."});


Object.assign(T.EN,{officialTikTok:"OFFICIAL TIKTOK",scanQr:"CLICK OR SCAN QR →",worldService:"WORLDWIDE SERVICE",performanceData:"PERFORMANCE DATA",worldwideFileService:"WORLDWIDE FILE SERVICE",dynoPerformance:"DYNO PERFORMANCE",rpmLabel:"ENGINE SPEED (RPM)",legendStock:"STOCK PS",databaseLabel:"DATABASE",resultsLabel:"HABIBI PERFORMANCE RESULTS",resultsTitle:'CUSTOMER <span>RESULTS</span>',resultsSub:"Selected performance examples. Actual output depends on vehicle condition and setup.",result1:"More power and noticeably better throttle response.",result2:"Smooth power delivery and noticeably more torque.",result3:"Sharper, stronger and still suitable for everyday driving.",rev1:"“Top service and a great result! My car feels new again. More power and faster response.”",rev2:"“Professional, fast and honest. Stage 1 made an immediately noticeable difference.”",rev3:"“Great advice and fast processing. The car runs cleanly and noticeably stronger.”",rev4:"“Very professional and fast. The car pulls much better while still running cleanly.”",rev5:"“Great communication and a very smooth result. More torque was immediately noticeable.”",rev6:"“Fast, serious service. The car responds much better after the modification.”",footerText:"© 2026 HABIBI PERFORMANCE • ECU TUNING • WORLDWIDE SERVICE"});
Object.assign(T.DE,{officialTikTok:"OFFIZIELLES TIKTOK",scanQr:"KLICKEN ODER QR SCANNEN →",worldService:"WELTWEITER SERVICE",performanceData:"LEISTUNGSDATEN",worldwideFileService:"WELTWEITER FILE SERVICE",dynoPerformance:"DYNO LEISTUNG",rpmLabel:"DREHZAHL (RPM)",legendStock:"SERIE PS",databaseLabel:"DATENBANK",resultsLabel:"HABIBI PERFORMANCE ERGEBNISSE",resultsTitle:'KUNDEN <span>ERGEBNISSE</span>',resultsSub:"Ausgewählte Performance-Beispiele. Die tatsächliche Leistung hängt vom Fahrzeugzustand und Setup ab.",result1:"Mehr Leistung und deutlich besseres Ansprechverhalten.",result2:"Saubere Leistungsentfaltung und spürbar mehr Drehmoment.",result3:"Direkter, kräftiger und trotzdem alltagstauglich.",rev1:"„Top Service und mega Ergebnis! Mein Auto fühlt sich wie neu an. Mehr Leistung und schnelleres Ansprechverhalten.“",rev2:"„Professionell, schnell und ehrlich. Stage 1 gemacht und der Unterschied ist sofort spürbar.“",rev3:"„Sehr gute Beratung und schnelle Bearbeitung. Auto läuft sauber und deutlich stärker.“",rev4:"„Sehr professionell und schnell. Das Auto zieht deutlich besser und fährt trotzdem sauber.“",rev5:"„Sehr gute Kommunikation und ein sauberes Ergebnis. Mehr Drehmoment ist sofort spürbar.“",rev6:"„Schneller und seriöser Service. Das Auto reagiert nach der Optimierung deutlich besser.“",footerText:"© 2026 HABIBI PERFORMANCE • ECU TUNING • WELTWEITER SERVICE"});
Object.assign(T.BS,{officialTikTok:"SLUŽBENI TIKTOK",scanQr:"KLIKNI ILI SKENIRAJ QR →",worldService:"USLUGA ŠIROM SVIJETA",performanceData:"PODACI O PERFORMANSAMA",worldwideFileService:"FILE SERVIS ŠIROM SVIJETA",dynoPerformance:"DYNO PERFORMANSE",rpmLabel:"BROJ OBRTAJA (RPM)",legendStock:"FABRIČKI PS",databaseLabel:"BAZA PODATAKA",resultsLabel:"HABIBI PERFORMANCE REZULTATI",resultsTitle:'REZULTATI <span>MUŠTERIJA</span>',resultsSub:"Odabrani primjeri performansi. Stvarna snaga zavisi od stanja vozila i setupa.",result1:"Više snage i osjetno bolji odziv na gas.",result2:"Čist razvoj snage i osjetno više obrtnog momenta.",result3:"Direktniji, snažniji i i dalje odličan za svakodnevnu vožnju.",rev1:"„Top usluga i odličan rezultat! Auto se ponaša kao novo. Više snage i brži odziv.“",rev2:"„Profesionalno, brzo i pošteno. Nakon Stage 1 razlika se odmah osjeti.“",rev3:"„Odličan savjet i brza obrada. Auto radi čisto i osjetno je snažniji.“",rev4:"„Vrlo profesionalno i brzo. Auto mnogo bolje vuče, a i dalje radi čisto.“",rev5:"„Odlična komunikacija i veoma čist rezultat. Više obrtnog momenta se odmah osjeti.“",rev6:"„Brza i ozbiljna usluga. Auto mnogo bolje reaguje nakon dorade.“",footerText:"© 2026 HABIBI PERFORMANCE • ECU TUNING • USLUGA ŠIROM SVIJETA"});
function tr(k){return T[lang][k]||k}
function arr(x){if(Array.isArray(x))return x; if(x&&Array.isArray(x.data))return x.data; if(x&&Array.isArray(x.results))return x.results; return []}
function textVal(x){if(typeof x==='string'||typeof x==='number')return String(x); return String(x?.name??x?.Make??x?.Model??x?.Generation??'')}
async function api(path){let r=await fetch(path);if(!r.ok)throw Error('catalogue');return r.json()}
function opts(el,a,label){el.innerHTML=`<option value="">${label}</option>`+[...new Set(a.filter(Boolean))].sort().map(v=>`<option value="${String(v).replaceAll('"','&quot;')}">${v}</option>`).join('');el.disabled=false}
function reset(el,l){el.innerHTML=`<option value="">${l}</option>`;el.disabled=true}
function setLang(l){lang=l;try{localStorage.setItem("hpLang",l)}catch(e){};document.documentElement.lang=l==="DE"?"de":l==="EN"?"en":"bs";document.querySelectorAll("[data-i]").forEach(e=>{let v=tr(e.dataset.i);if(v)e.innerHTML=v});document.querySelectorAll("[data-ph]").forEach(e=>e.placeholder=tr(e.dataset.ph));}
async function init(){
 try{let m=arr(await api('/api/tuning/makes')).map(textVal);opts($('make'),m,tr('selMake'));$('brandsCount').textContent=m.length+'+';$('carsCount').textContent='LIVE';}
 catch(e){$('result').innerHTML=`<div class="tune"><div class="tuneHead"><h3>${tr('unavailable')}</h3></div></div>`}
 $('make').onchange=loadModels;$('model').onchange=loadGenerations;$('gen').onchange=loadResults;$('engine').onchange=()=>{let c=cars.find(x=>String(x.id)===$('engine').value);if(c)show(c)};
 $('quickSearch').style.display='none';$('suggestions').style.display='none';renderPopular();let saved='EN';try{saved=localStorage.getItem('hpLang')||'EN'}catch(e){};if(!['EN','DE','BS'].includes(saved))saved='EN';$('lang').value=saved;setLang(saved)
}
async function loadModels(){cars=[];reset($('model'),tr('selModel'));reset($('gen'),tr('selGen'));reset($('engine'),tr('selEngine'));if(!$('make').value)return;let a=arr(await api('/api/tuning/models?make='+encodeURIComponent($('make').value))).map(textVal);opts($('model'),a,tr('selModel'))}
async function loadGenerations(){cars=[];reset($('gen'),tr('selGen'));reset($('engine'),tr('selEngine'));if(!$('model').value)return;let q=`make=${encodeURIComponent($('make').value)}&model=${encodeURIComponent($('model').value)}`;let a=arr(await api('/api/tuning/generations?'+q)).map(textVal);opts($('gen'),a,tr('selGen'))}
async function loadResults(){reset($('engine'),tr('loading'));if(!$('gen').value)return;let q=`make=${encodeURIComponent($('make').value)}&model=${encodeURIComponent($('model').value)}&generation=${encodeURIComponent($('gen').value)}`;cars=arr(await api('/api/tuning/results?'+q));opts($('engine'),cars.map(c=>c.Engine||c.engine),tr('selEngine'));[...$('engine').options].forEach((o,i)=>{if(i)o.value=String(cars[i-1].id??i-1)})}
function n(v){let m=String(v??'').match(/[\d.]+/);return m?Number(m[0]):0}
function show(c){let sh=n(c.BHP_standard),th=n(c.BHP_tuned),sn=n(c.TORQUE_standard),tn=n(c.TORQUE_tuned);let title=`${c.Make||''} ${c.Model||''} — ${c.Engine||''}`;let slug=[c.Make,c.Model,c.Generation,c.Engine].filter(Boolean).join('-');let ecu=c.Engine_ECU||c.ECU||c.ecu||'';$('result').innerHTML=`<div class="tune"><div class="tuneHead"><small>${c.Generation||''}</small><span class="dataBadge verified">LIVE DATA</span><h3>${title}</h3></div><div class="ecuExact"><div><small>${tr('ecuUnit')}</small><strong>${ecu||tr('ecuUnknown')}</strong></div><div class="ecuHint">${tr('ecuHint')}</div></div><div class="power"><div><small>${tr('original')}</small><strong>${sh||'—'} PS</strong><span>${sn||'—'} Nm</span></div><div class="hot"><small>${tr('tuned')}</small><strong>${th||'—'} PS</strong><span>${tn||'—'} Nm</span></div></div><div class="gains"><div class="gain">+${Math.max(0,th-sh)} PS / +${Math.max(0,tn-sn)} Nm</div></div><div class="actions"><a href="${portal}?vehicle=${encodeURIComponent(slug)}">${tr('order')}</a><small>${tr('estimate')}</small></div></div>`;$('result').scrollIntoView({behavior:'smooth',block:'nearest'})}
function selectCurrent(){let c=cars.find(x=>String(x.id)===$('engine').value);if(c)show(c)}
function renderPopular(){$('popularGrid').innerHTML=''}
init();
document.addEventListener('DOMContentLoaded',()=>{const cards=[...document.querySelectorAll('.reviewCard')],dots=[...document.querySelectorAll('.reviewDots button')];if(!cards.length)return;let n=0,t;const show=i=>{n=i;cards.forEach((c,j)=>c.classList.toggle('active',j===i));dots.forEach((d,j)=>d.classList.toggle('on',j===i))};const auto=()=>{clearInterval(t);t=setInterval(()=>show((n+1)%cards.length),5000)};dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);auto()}));auto()});

document.addEventListener("DOMContentLoaded",()=>{
  document.querySelectorAll(".reviewStack").forEach((stack,stackIndex)=>{
    const cards=[...stack.querySelectorAll(".reviewCard")];
    const dots=[...stack.querySelectorAll(".reviewDots button")];
    if(!cards.length)return;
    let n=0,t;
    const show=i=>{
      n=i;
      cards.forEach((c,j)=>c.classList.toggle("active",j===i));
      dots.forEach((d,j)=>d.classList.toggle("on",j===i));
    };
    dots.forEach((d,i)=>d.addEventListener("click",()=>{show(i);clearInterval(t);t=setInterval(()=>show((n+1)%cards.length),5500+stackIndex*500)}));
    t=setInterval(()=>show((n+1)%cards.length),5500+stackIndex*500);
  });
});
