let cars=[],lang="DE";const $=x=>document.getElementById(x),portal="https://portal.habibi-performance.com/login";
const T={DE:{navHome:"HOME",navDatabase:"ECU DATENBANK",navDyno:"DYNO ERGEBNISSE",navServices:"SERVICES",filePortal:"FILE PORTAL",officialPartner:"OFFIZIELLER PARTNER",clickScan:"Klicken oder scannen",verifiedCustomer:"VERIFIZIERTER KUNDE",stockLabel:"SERIE",powerLabel:"LEISTUNG",torqueLabel:"DREHMOMENT",gainLabel:"ZUWACHS",review:"„Top Service und mega Ergebnis! Mein Auto fühlt sich wie neu an. Mehr Leistung, schnelleres Ansprechverhalten. Klare Empfehlung!“",scan:"SCANNEN & FOLGEN",partners:"PARTNER",partners_sub:"Partner-Logos später hier einfügen",headline:'WIE VIEL <span>LEISTUNG</span> STECKT IN DEINEM AUTO?',sub:"Wähle dein Fahrzeug und sieh Serienleistung und verfügbares Tuning-Potenzial.",make:"HERSTELLER",model:"MODELL",gen:"GENERATION",engine:"MOTOR / LEISTUNG",search:"FAHRZEUG FINDEN",quick:"Fahrzeug über Hersteller, Modell und Generation wählen",safe:"100% SICHER & ZUVERLÄSSIG",safeSub:"Deine Daten sind bei uns sicher.",fast:"SCHNELLE LIEFERUNG",fastSub:"Schnelle Bearbeitung & Lieferung.",quality:"PROFESSIONELLE QUALITÄT",qualitySub:"Geprüfte Tuning-Files.",world:"Kunden weltweit.",brands:"MARKEN",cars:"FAHRZEUGE",dynoTitle:'ECHTE PARAMETER. <span>KLARE LEISTUNG.</span>',dynoSub:"Professionelle Darstellung – nur die Werte, die zählen.",servicesTitle:'UNSERE <span>LEISTUNGEN</span>',s1:"Performance-Kalibrierungen für unterstützte Fahrzeuge.",s2:"Professionelle Motor- und Getriebe-Dateilösungen.",s3:"Individuelle Lösungen passend zum Fahrzeug.",s4:"Upload und Download über das File Portal.",popular:'BELIEBTE <span>FAHRZEUGE</span>',faqTitle:'HÄUFIGE <span>FRAGEN</span>',q1:"Ist die angezeigte Leistung garantiert?",a1:"Nein. Das tatsächliche Ergebnis hängt von ECU, Kraftstoff, Hardware und Fahrzeugzustand ab.",q2:"Muss ich zu euch kommen?",a2:"Nein. Der File Service ist weltweit über das Portal verfügbar.",q3:"Wie bestelle ich eine Datei?",a3:"Fahrzeug auswählen und im File Portal fortfahren.",ready:"BEREIT FÜR MEHR LEISTUNG?",readySub:"Datei hochladen, Credits kaufen und fertige Datei über das Portal herunterladen.",selMake:"Hersteller wählen",selModel:"Modell wählen",selGen:"Generation wählen",selEngine:"Motor wählen",original:"SERIE",tuned:"TUNING",order:"DATEI BESTELLEN →",estimate:"Leistungsangaben aus dem Fahrzeugkatalog. Das reale Ergebnis kann je nach Fahrzeugzustand und Hardware abweichen.",loading:"WIRD GELADEN…",unavailable:"Daten momentan nicht verfügbar."},
BS:{navHome:"POČETNA",navDatabase:"ECU BAZA",navDyno:"DYNO REZULTATI",navServices:"USLUGE",filePortal:"FILE PORTAL",officialPartner:"SLUŽBENI PARTNER",clickScan:"Klikni ili skeniraj",verifiedCustomer:"POTVRĐENA MUŠTERIJA",stockLabel:"FABRIČKI",powerLabel:"SNAGA",torqueLabel:"OBRTNI MOMENT",gainLabel:"DOBITAK",review:"„Top usluga i odličan rezultat! Auto se ponaša kao novo. Više snage i bolji odziv. Svaka preporuka!“",scan:"SKENIRAJ & ZAPRATI",partners:"PARTNERI",partners_sub:"Logoe partnera možeš dodati kasnije",headline:'KOLIKO <span>SNAGE</span> SE KRIJE U TVOM AUTU?',sub:"Izaberi vozilo i pogledaj fabričku snagu i dostupni tuning potencijal.",make:"MARKA",model:"MODEL",gen:"GENERACIJA",engine:"MOTOR / SNAGA",search:"PRONAĐI VOZILO",quick:"Izaberi marku, model i generaciju",safe:"100% SIGURNO & POUZDANO",safeSub:"Tvoji podaci su sigurni.",fast:"BRZA ISPORUKA",fastSub:"Brza obrada i isporuka.",quality:"PROFESIONALNI KVALITET",qualitySub:"Provjereni tuning fajlovi.",world:"Mušterije širom svijeta.",brands:"BRENDOVA",cars:"VOZILA",dynoTitle:'PRAVI PARAMETRI. <span>JASNA SNAGA.</span>',dynoSub:"Profesionalan prikaz – samo parametri koji su bitni.",servicesTitle:'NAŠE <span>USLUGE</span>',s1:"Performance kalibracije za podržana vozila.",s2:"Profesionalna ECU i TCU rješenja.",s3:"Individualna rješenja za konkretno vozilo.",s4:"Upload i download preko File Portala.",popular:'POPULARNA <span>VOZILA</span>',faqTitle:'ČESTA <span>PITANJA</span>',q1:"Da li je prikazana snaga garantovana?",a1:"Ne. Stvarni rezultat zavisi od ECU-a, goriva, hardvera i stanja vozila.",q2:"Moram li doći kod vas?",a2:"Ne. File servis je dostupan worldwide preko portala.",q3:"Kako naručujem file?",a3:"Izaberi vozilo i nastavi preko File Portala.",ready:"SPREMAN ZA VIŠE SNAGE?",readySub:"Uploaduj file, kupi kredite i preuzmi gotov file preko portala.",selMake:"Izaberi marku",selModel:"Izaberi model",selGen:"Izaberi generaciju",selEngine:"Izaberi motor",original:"FABRIČKI",tuned:"TUNING",order:"NARUČI FILE →",estimate:"Podaci o snazi dolaze iz kataloga vozila. Stvarni rezultat može odstupati zavisno od stanja vozila i hardvera.",loading:"UČITAVANJE…",unavailable:"Podaci trenutno nisu dostupni."},
EN:{navHome:"HOME",navDatabase:"ECU DATABASE",navDyno:"DYNO RESULTS",navServices:"SERVICES",filePortal:"FILE PORTAL",officialPartner:"OFFICIAL PARTNER",clickScan:"Click or scan",verifiedCustomer:"VERIFIED CUSTOMER",stockLabel:"STOCK",powerLabel:"POWER",torqueLabel:"TORQUE",gainLabel:"GAIN",review:"“Top service and an amazing result! My car feels new again. More power and faster response. Highly recommended!”",scan:"SCAN & FOLLOW",partners:"PARTNERS",partners_sub:"Partner logos can be added later",headline:'HOW MUCH <span>POWER</span> IS HIDING IN YOUR CAR?',sub:"Select your vehicle and see stock power and available tuning potential.",make:"MAKE",model:"MODEL",gen:"GENERATION",engine:"ENGINE / POWER",search:"FIND VEHICLE",quick:"Select make, model and generation",safe:"100% SAFE & RELIABLE",safeSub:"Your data is safe with us.",fast:"FAST DELIVERY",fastSub:"Fast processing & delivery.",quality:"PROFESSIONAL QUALITY",qualitySub:"Verified tuning files.",world:"Customers worldwide.",brands:"BRANDS",cars:"VEHICLES",dynoTitle:'REAL PARAMETERS. <span>CLEAR PERFORMANCE.</span>',dynoSub:"Professional display – only the values that matter.",servicesTitle:'OUR <span>SERVICES</span>',s1:"Performance calibrations for supported vehicles.",s2:"Professional ECU and TCU file solutions.",s3:"Individual vehicle-specific solutions.",s4:"Upload and download through the File Portal.",popular:'POPULAR <span>VEHICLES</span>',faqTitle:'FREQUENT <span>QUESTIONS</span>',q1:"Is the displayed power guaranteed?",a1:"No. Actual output depends on ECU, fuel, hardware and vehicle condition.",q2:"Do I need to visit you?",a2:"No. File service is available worldwide through the portal.",q3:"How do I order a file?",a3:"Select your vehicle and continue through the File Portal.",ready:"READY FOR MORE POWER?",readySub:"Upload a file, buy credits and download the finished file through the portal.",selMake:"Select manufacturer",selModel:"Select model",selGen:"Select generation",selEngine:"Select engine",original:"STOCK",tuned:"TUNING",order:"ORDER FILE →",estimate:"Power data comes from the vehicle catalogue. Real-world results may vary with vehicle condition and hardware.",loading:"LOADING…",unavailable:"Data currently unavailable."}};
function tr(k){return T[lang][k]||k}
function arr(x){if(Array.isArray(x))return x; if(x&&Array.isArray(x.data))return x.data; if(x&&Array.isArray(x.results))return x.results; return []}
function textVal(x){if(typeof x==='string'||typeof x==='number')return String(x); return String(x?.name??x?.Make??x?.Model??x?.Generation??'')}
async function api(path){let r=await fetch(path);if(!r.ok)throw Error('catalogue');return r.json()}
function opts(el,a,label){el.innerHTML=`<option value="">${label}</option>`+[...new Set(a.filter(Boolean))].sort().map(v=>`<option value="${String(v).replaceAll('"','&quot;')}">${v}</option>`).join('');el.disabled=false}
function reset(el,l){el.innerHTML=`<option value="">${l}</option>`;el.disabled=true}
function setLang(l){lang=l;document.documentElement.lang=l==="DE"?"de":l==="EN"?"en":"bs";document.querySelectorAll("[data-i]").forEach(e=>{let v=tr(e.dataset.i);if(v)e.innerHTML=v});document.querySelectorAll("[data-ph]").forEach(e=>e.placeholder=tr(e.dataset.ph));}
async function init(){
 try{let m=arr(await api('/api/tuning/makes')).map(textVal);opts($('make'),m,tr('selMake'));$('brandsCount').textContent=m.length+'+';$('carsCount').textContent='LIVE';}
 catch(e){$('result').innerHTML=`<div class="tune"><div class="tuneHead"><h3>${tr('unavailable')}</h3></div></div>`}
 $('make').onchange=loadModels;$('model').onchange=loadGenerations;$('gen').onchange=loadResults;$('engine').onchange=()=>{let c=cars.find(x=>String(x.id)===$('engine').value);if(c)show(c)};
 $('quickSearch').style.display='none';$('suggestions').style.display='none';renderPopular();setLang('DE')
}
async function loadModels(){cars=[];reset($('model'),tr('selModel'));reset($('gen'),tr('selGen'));reset($('engine'),tr('selEngine'));if(!$('make').value)return;let a=arr(await api('/api/tuning/models?make='+encodeURIComponent($('make').value))).map(textVal);opts($('model'),a,tr('selModel'))}
async function loadGenerations(){cars=[];reset($('gen'),tr('selGen'));reset($('engine'),tr('selEngine'));if(!$('model').value)return;let q=`make=${encodeURIComponent($('make').value)}&model=${encodeURIComponent($('model').value)}`;let a=arr(await api('/api/tuning/generations?'+q)).map(textVal);opts($('gen'),a,tr('selGen'))}
async function loadResults(){reset($('engine'),tr('loading'));if(!$('gen').value)return;let q=`make=${encodeURIComponent($('make').value)}&model=${encodeURIComponent($('model').value)}&generation=${encodeURIComponent($('gen').value)}`;cars=arr(await api('/api/tuning/results?'+q));opts($('engine'),cars.map(c=>c.Engine||c.engine),tr('selEngine'));[...$('engine').options].forEach((o,i)=>{if(i)o.value=String(cars[i-1].id??i-1)})}
function n(v){let m=String(v??'').match(/[\d.]+/);return m?Number(m[0]):0}
function show(c){let sh=n(c.BHP_standard),th=n(c.BHP_tuned),sn=n(c.TORQUE_standard),tn=n(c.TORQUE_tuned);let title=`${c.Make||''} ${c.Model||''} — ${c.Engine||''}`;let slug=[c.Make,c.Model,c.Generation,c.Engine].filter(Boolean).join('-');$('result').innerHTML=`<div class="tune"><div class="tuneHead"><small>${c.Generation||''}${c.Engine_ECU?' • ECU '+c.Engine_ECU:''}</small><span class="dataBadge verified">LIVE DATA</span><h3>${title}</h3></div><div class="power"><div><small>${tr('original')}</small><strong>${sh||'—'} PS</strong><span>${sn||'—'} Nm</span></div><div class="hot"><small>${tr('tuned')}</small><strong>${th||'—'} PS</strong><span>${tn||'—'} Nm</span></div></div><div class="gains"><div class="gain">+${Math.max(0,th-sh)} PS / +${Math.max(0,tn-sn)} Nm</div></div><div class="actions"><a href="${portal}?vehicle=${encodeURIComponent(slug)}">${tr('order')}</a><small>${tr('estimate')}</small></div></div>`;$('result').scrollIntoView({behavior:'smooth',block:'nearest'})}
function selectCurrent(){let c=cars.find(x=>String(x.id)===$('engine').value);if(c)show(c)}
function renderPopular(){$('popularGrid').innerHTML=''}
init();
document.addEventListener('DOMContentLoaded',()=>{const cards=[...document.querySelectorAll('.reviewCard')],dots=[...document.querySelectorAll('.reviewDots button')];if(!cards.length)return;let n=0,t;const show=i=>{n=i;cards.forEach((c,j)=>c.classList.toggle('active',j===i));dots.forEach((d,j)=>d.classList.toggle('on',j===i))};const auto=()=>{clearInterval(t);t=setInterval(()=>show((n+1)%cards.length),5000)};dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);auto()}));auto()});

document.addEventListener("DOMContentLoaded",()=>{
  document.querySelectorAll(".reviewStack").forEach((stack,stackIndex)=>{
    const cards=[...stack.querySelectorAll(".reviewCard")];
    const dots=[...stack.querySelectorAll(".reviewDots button")];
    if(!cards.length)return;
    let n=0,t;
    const show=i=>{
      n=i;
      cards.forEach((c,j)=>c.classList.toggle("active",j===i));
      dots.forEach((d,j)=>d.classList.toggle("on",j===i));
    };
    dots.forEach((d,i)=>d.addEventListener("click",()=>{show(i);clearInterval(t);t=setInterval(()=>show((n+1)%cards.length),5500+stackIndex*500)}));
    t=setInterval(()=>show((n+1)%cards.length),5500+stackIndex*500);
  });
});

document.addEventListener("change", function(e){
  if(e.target.id === "lang"){
    const mobile = document.getElementById("mobileLang");
    if(mobile) mobile.value = e.target.value;
  }

  if(e.target.id === "mobileLang"){
    const desktop = document.getElementById("lang");
    if(desktop) desktop.value = e.target.value;
  }
});
